language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script: 
  - "psql -c 'create database store_manager;' -U mwangemi"
  - psql -c "create user mwangemi with password '123';" -U mwangemi   
  
# command to run tests
script:
- nosetests tests/V2/* --with-coverage --cover-package=app && coverage report

# run coverage tests
after_success:
- coveralls
- codeclimate-test-reporter